export const ACL = {
  superadmin: {
    kendaraan: ["create", "read", "update", "delete"],
    alatBerat: ["create", "read", "update", "delete"],
    alatKerja: ["create", "read", "update", "delete"],
    ac: ["create", "read", "update", "delete"],
    tanah: ["create", "read", "update", "delete"],
    tanaman: ["create", "read", "update", "delete"],
    servisAc: ["create", "read", "update", "delete"],
    servisKendaraan: ["create", "read", "update", "delete"],
    servisAlatBerat: ["create", "read", "update", "delete"],
    servisAlatKerja: ["create", "read", "update", "delete"],
    serberAc: ["create", "read", "update", "delete"],
    serberKendaraan: ["create", "read", "update", "delete"],
    serberAlatBerat: ["create", "read", "update", "delete"],
    serberAlatKera: ["create", "read", "update", "delete"],
  },
  admin: {
    kendaraan: ["create", "read"],
    alatBerat: ["create", "read"],
    alatKerja: ["create", "read"],
    ac: ["create", "read"],
    tanah: ["create", "read"],
    tanaman: ["create", "read"],
    servisAc: ["create", "read"],
    servisKendaraan: ["create", "read"],
    servisAlatBerat: ["create", "read"],
    servisAlatKerja: ["create", "read"],
    serberAc: ["create", "read"],
    serberKendaraan: ["create", "read"],
    serberAlatBerat: ["create", "read"],
    serberAlatKerja: ["create", "read"],
  },
};
